app:
  build:
    context: ./
    dockerfile: Dockerfile 
  image: flexguru
  container_name: flexguru-app
  restart: unless-stopped
  working_dir: /var/www/
  volumes:
    - ./:/var/www 
  networks:
    -flexguru

nginx:
  image: nginx: 1.17-alpine 
  container_name: flexguru-nginx
  restart: unless-stopped 
  ports:
    -8000:80
  volumes:
    - ./:/var/www
    - ./docker-compose/nginx:/etc/nginx/conf.d 
  networks:
    -flexguru 

db:
  image: mysql:latest
  container_name: flexguru-db
  restart: unless-stopped 
  environment: 
    MYSQL_DATABASE: flexgurudb
    MYSQL_ROOT_PASSWORD: Kusalmendis123!
    MYSQL_PASSWORD: Kusalmendis123!
    MYSQL_USER: fg-dbadmin
    SERVICE_TAGS: dev 
    SERVICE_NAME: mysql 
  volumes:
    - ./docker-compose/mysql:/docker-entrypoint-initdb.d 
  networks: 
    -flexguru